version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=todoApi"
#      - "POSTGRES_HOST_AUTH_METHOD=trust"
#    volumes:
#      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"