spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/todoApi
    username: postgres
    password: pass

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  application:
    name: TodoApp
    version: 1.0
    description: "My task Todo application is where you can register, due to which the necessary
     records and notes are created.
     Technologies used Spring Data JPA, Spring Security, Swagger, Spring boot, Spring AOP,
      Spring Validation, ModelMapper, Liquibase"
  contact:
    name: Aleksey Paslenov
    email: alekseypaslenov@gmail.com
